# Generated by Django 5.1.1 on 2024-09-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unspsc', models.CharField(help_text="Código UNSPSC, separado por ';' si hay varios", max_length=100)),
                ('dependencia_responsable', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_estimada_inicio', models.DateField(blank=True, help_text='Fecha estimada de inicio del proceso de selección', null=True)),
                ('fecha_estimada_ofertas', models.DateField(blank=True, help_text='Fecha estimada de presentación de ofertas', null=True)),
                ('duracion_numero', models.IntegerField(blank=True, help_text='Duración del contrato en número', null=True)),
                ('duracion_intervalo', models.CharField(choices=[('dias', 'Días'), ('meses', 'Meses'), ('años', 'Años')], default='meses', max_length=20)),
                ('modalidad_seleccion', models.CharField(max_length=255)),
                ('fuente_recursos', models.CharField(max_length=255)),
                ('valor_total_estimado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_vigencia_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('requiere_vigencias_futuras', models.BooleanField(default=False)),
                ('estado_vigencias_futuras', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_contratacion', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('nombre_responsable', models.CharField(max_length=255)),
                ('telefono_responsable', models.CharField(blank=True, max_length=20, null=True)),
                ('email_responsable', models.EmailField(max_length=254)),
                ('ley_alimentos_30_por_ciento', models.BooleanField(default=False, help_text='Debe cumplir con el 30% de la Ley 2046 de 2020')),
                ('contrato_incluye_bienes_servicios', models.BooleanField(default=False, help_text='¿El contrato incluye bienes y servicios distintos a alimentos?')),
                ('profesional_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_adquisiciones', models.BooleanField(default=False)),
                ('ficha_tecnica', models.BooleanField(default=False)),
                ('solicitud_cotizacion', models.BooleanField(default=False)),
                ('estudio_mercado', models.BooleanField(default=False)),
                ('solicitud_cdp', models.BooleanField(default=False)),
                ('estudio_previo', models.BooleanField(default=False)),
                ('invitacion_presentar_propuesta', models.BooleanField(default=False)),
                ('avance_pc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avance_general', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_asignacion_proceso', models.DateField(blank=True, null=True)),
                ('profesional_abogado', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_programada_suscripcion', models.DateField(blank=True, null=True)),
                ('fecha_real_suscripcion', models.DateField(blank=True, null=True)),
                ('recepcion_propuesta', models.BooleanField(default=False)),
                ('evaluacion_juridica', models.BooleanField(default=False)),
                ('evaluacion_tecnica', models.BooleanField(default=False)),
                ('minuta_contrato', models.BooleanField(default=False)),
                ('solicitud_rp', models.BooleanField(default=False)),
                ('comunicacion_supervisor', models.BooleanField(default=False)),
                ('acta_inicio', models.BooleanField(default=False)),
                ('publicacion_secop', models.BooleanField(default=False)),
                ('avance_pos_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('excel_licitaciones', models.BooleanField(default=False)),
                ('documentos_escanados', models.BooleanField(default=False)),
                ('liquidacion', models.BooleanField(default=False)),
                ('avance_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
