# Generated by Django 5.1.1 on 2024-09-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_contrato_acta_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='codigo_unspsc',
            field=models.CharField(help_text='Código UNSPSC', max_length=100),
        ),
    ]
