# Generated by Django 5.1.1 on 2024-09-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contrato_codigo_unspsc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
