# Generated by Django 5.1.1 on 2024-09-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unspsc', models.CharField(help_text='Código UNSPSC', max_length=100)),
                ('dependencia_responsable', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_estimada_inicio', models.DateField(blank=True, help_text='Fecha estimada de inicio del proceso de selección', null=True)),
                ('fecha_estimada_ofertas', models.DateField(blank=True, help_text='Fecha estimada de presentación de ofertas', null=True)),
            ],
        ),
    ]
