# Generated by Django 5.1.1 on 2024-09-20 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_contrato_alerta_dias_finalizar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('adicion_1', models.CharField(max_length=255)),
                ('adicion_2', models.CharField(blank=True, max_length=255, null=True)),
                ('adicion_3', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nit_o_cc', models.CharField(max_length=100)),
                ('representante_legal', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_agregado', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prorroga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('justificacion', models.TextField()),
                ('nueva_fecha_finalizacion', models.DateField()),
                ('fecha_suspension', models.DateField(blank=True, null=True)),
                ('fecha_reinicio', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nit_o_cc', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_agregado', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='cdp_fecha',
            new_name='CDP_fecha',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='rp_fecha',
            new_name='RP_fecha',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha_aprobacion_poliza',
            new_name='fecha_poliza_aprobacion',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha_expedicion_poliza',
            new_name='fecha_poliza_expedicion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='alerta_dias_finalizar',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='alerta_entrega_fisico',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='alerta_secop',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cargo_supervisor',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cc_supervisor',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='documentos_drive',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='documentos_secop',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='email_contratista',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='email_supervisor',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='estado_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_aclaratoria',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_acta_inicio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_acta_liquidacion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_ampliacion_suspension',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_entrega_carpeta_fisico',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_finalizacion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_modificatoria',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_prorroga',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_reinicio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_suscripcion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_suspension',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='finalizado',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fuente_financiacion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='funcionario_a_cargo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='justificacion_aclaratoria',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='justificacion_modificatoria',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='justificacion_prorroga',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='justificacion_suspension',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nit_contratista',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nit_representante_legal',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nombre_contratista',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nueva_fecha_finalizacion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='numero_cdp',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='numero_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='numero_poliza',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='numero_rp',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='objeto',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='plazo_ejecucion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='representante_legal',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='rubro_presupuestal',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='telefono_contratista',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tiene_entrada_almacen',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_contratacion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='union_temporal_consorcio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_adicion_1',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_adicion_2',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_adicion_3',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_estimado_actual',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_final_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_total_adiciones',
        ),
        migrations.AddField(
            model_name='contrato',
            name='CDP_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='RP_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='estado_solicitud_vigencias_futuras',
            field=models.CharField(blank=True, choices=[(0, 'NA'), (1, 'No solicitadas'), (2, 'Solicitadas'), (3, 'Aprobadas')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_asignacion_proceso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_presentacion_ofertas',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_seleccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_suscripcion_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fuente_recursos',
            field=models.CharField(blank=True, choices=[(0, 'Recursos propios'), (1, 'Presupuesto de entidad nacional'), (2, 'Regalías'), (3, 'Recursos de crédito'), (4, 'SGP'), (5, 'No Aplica')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='minuta_contrato',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='modalidad_seleccion',
            field=models.CharField(blank=True, choices=[('CCE-01', 'Solicitud de información a los Proveedores'), ('CCE-02', 'Licitación pública'), ('CCE-17', 'Licitación pública (Obra pública)'), ('CCE-03', 'Concurso de méritos con precalificación (descontinuado)'), ('CCE-04', 'Concurso de méritos abierto (descontinuado)'), ('CCE-20-Concurso_Meritos_Sin_Lista_Corta_1Sobre', 'Concurso de méritos abierto'), ('CCE-05', 'Contratación directa (con ofertas)'), ('CCE-06', 'Selección abreviada menor cuantía'), ('CCE-18-Seleccion_Abreviada_Menor_Cuantia_Sin_Manifestacion_Interes', 'Selección Abreviada Menor Cuantia sin Manifestación de Interés'), ('CCE-19-Concurso_Meritos_Con_Lista_Corta_1Sobre', 'Concurso de méritos con precalificación'), ('CCE-07', 'Selección abreviada subasta inversa'), ('CCE-10', 'Mínima cuantía'), ('CCE-11||01', 'Contratación régimen especial - Selección de comisionista')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='num_contrato',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='num_poliza',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='plazo_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='plazo_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='presupuesto_programado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='publicacion_secop',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('CCE-01', 'Solicitud de información a los Proveedores'), ('CCE-02', 'Licitación pública'), ('CCE-17', 'Licitación pública (Obra pública)'), ('CCE-03', 'Concurso de méritos con precalificación (descontinuado)'), ('CCE-04', 'Concurso de méritos abierto (descontinuado)'), ('CCE-20-Concurso_Meritos_Sin_Lista_Corta_1Sobre', 'Concurso de méritos abierto'), ('CCE-05', 'Contratación directa (con ofertas)'), ('CCE-06', 'Selección abreviada menor cuantía'), ('CCE-18-Seleccion_Abreviada_Menor_Cuantia_Sin_Manifestacion_Interes', 'Selección Abreviada Menor Cuantia sin Manifestación de Interés'), ('CCE-19-Concurso_Meritos_Con_Lista_Corta_1Sobre', 'Concurso de méritos con precalificación'), ('CCE-07', 'Selección abreviada subasta inversa'), ('CCE-10', 'Mínima cuantía'), ('CCE-11||01', 'Contratación régimen especial - Selección de comisionista')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='clase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='codigo_unspsc',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dependencia_responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_estimada_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_estimada_ofertas',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='adicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.adicion'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.contratista'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='prorroga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.prorroga'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.supervisor'),
        ),
    ]
