# Generated by Django 5.1.1 on 2024-09-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_adicion_contratista_prorroga_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='codigo_unspsc',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='estado_solicitud_vigencias_futuras',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_asignacion_proceso',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_estimada_inicio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_estimada_ofertas',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_presentacion_ofertas',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_seleccion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='minuta_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='num_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='num_poliza',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo',
        ),
        migrations.AddField(
            model_name='contratista',
            name='nit_o_cc_representante_legal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='almacen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='documentos_cargados',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='estado_contrato',
            field=models.CharField(default='En Ejecución', max_length=200),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_liquidacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_contrato',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_poliza',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='rubro_presupuestal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contratacion',
            field=models.CharField(choices=[('noinfo', 'Sin Clasificar'), ('directa', 'Directa'), ('privada', 'Privada'), ('publica', 'Publica')], default='noinfo', max_length=600),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='fecha_agregado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='nit_o_cc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='clase',
            field=models.CharField(blank=True, choices=[('arrendamiento', 'Arrendamiento'), ('cesion_derechos_patrimoniales', 'Cesión Derechos Patrimoniales'), ('compraventa', 'Compraventa'), ('consultoria', 'Consultoría'), ('interadministrativo', 'Interadministrativo'), ('obra_publica', 'Obra Pública'), ('orden_compra_colombia_compra_eficiente', 'Orden Compra Colombia Compra Eficiente'), ('prestacion_servicios', 'Prestación de Servicios'), ('prestacion_servicios_compraventa', 'Prestación de Servicios y Compraventa'), ('prestacion_servicios_suministro', 'Prestación de Servicios y Suministro'), ('seguros', 'Seguros'), ('prestacion_servicios_profesionales', 'Prestación de Servicios Profesionales'), ('suministro', 'Suministro')], max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='descripcion',
            field=models.TextField(blank=True, default='no se ha presentado objeto', null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fuente_recursos',
            field=models.CharField(blank=True, choices=[(0, 'Recursos propios'), (1, 'Presupuesto de entidad nacional'), (2, 'Regalías'), (3, 'Recursos de crédito'), (4, 'SGP'), (5, 'No Aplica')], max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='modalidad_seleccion',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='publicacion_secop',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='fecha_agregado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='nit_o_cc',
            field=models.IntegerField(),
        ),
    ]
