# Generated by Django 5.1.1 on 2024-10-09 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workspace', '0008_remove_contrato_codigo_unspsc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos_adicionales',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fuente_recursos',
            field=models.CharField(blank=True, choices=[('recursos_propios', 'Recursos propios'), ('presupuesto_entidad_nacional', 'Presupuesto de entidad nacional'), ('regalias', 'Regalías'), ('recursos_credito', 'Recursos de crédito'), ('sgp', 'SGP'), ('no_aplica', 'No Aplica')], max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(choices=[('gestor', 'Gestor'), ('abogado', 'Abogado'), ('revisor', 'Revisor')], default='gestor', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rol',
            unique_together={('usuario', 'rol')},
        ),
    ]
