# Generated by Django 5.1.1 on 2024-11-04 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_rol_grupo_rol_permisos_adicionales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='clase',
            field=models.CharField(blank=True, choices=[('Arrendamiento', 'arrendamiento'), ('Cesión Derechos Patrimoniales', 'cesion_derechos_patrimoniales'), ('Compraventa', 'compraventa'), ('Consultoría', 'consultoria'), ('Interadministrativo', 'interadministrativo'), ('Obra Pública', 'obra_publica'), ('Orden Compra Colombia Compra Eficiente', 'orden_compra_colombia_compra_eficiente'), ('Prestación de Servicios', 'prestacion_servicios'), ('Prestación de Servicios y Compraventa', 'prestacion_servicios_compraventa'), ('Prestación de Servicios y Suministro', 'prestacion_servicios_suministro'), ('Seguros', 'seguros'), ('Prestación de Servicios Profesionales', 'prestacion_servicios_profesionales'), ('Suministro', 'suministro')], max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_poliza',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='El número de póliza debe ser un entero positivo.')]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='publicacion_secop',
            field=models.URLField(blank=True, max_length=600, null=True, validators=[django.core.validators.URLValidator(message='Ingrese una URL válida o deje el campo en blanco.')]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contratacion',
            field=models.CharField(choices=[('Sin Clasificar', 'Sin Clasificar'), ('Directa', 'Directa'), ('Privada', 'Privada'), ('Publica', 'Publica')], default='noinfo', max_length=600),
        ),
    ]
