# Generated by Django 5.1.1 on 2024-12-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_alter_contrato_contratista_alter_contrato_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='descripcion',
            new_name='objeto',
        ),
    ]
