# Generated by Django 5.1.1 on 2024-12-03 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0012_rename_descripcion_contrato_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='CDP_num',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='RP_num',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_contrato',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_poliza',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='El número de póliza debe ser un entero positivo.')]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='publicacion_secop',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
