# Generated by Django 5.1.1 on 2024-12-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_alter_contrato_cdp_num_alter_contrato_rp_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='CDP_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='RP_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
