# Generated by Django 5.1.1 on 2024-12-03 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0015_alter_contrato_numero_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='numero_poliza',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='El número de póliza debe ser un entero positivo.')]),
        ),
    ]
