# Generated by Django 5.1.1 on 2024-12-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0016_alter_contrato_numero_poliza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_publicacion_secop',
            field=models.DateField(blank=True, default='www.unillanos.edu.co', null=True),
        ),
    ]
