# Generated by Django 5.1.1 on 2024-12-13 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0017_alter_contrato_fecha_publicacion_secop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subscripcion', models.DateField(null=True)),
                ('motivo', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reinicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subscripcion', models.DateField(null=True)),
                ('fecha_terminacion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subscripcion', models.DateField(null=True)),
                ('plazo', models.DateField(null=True)),
                ('fecha_posible_reinicio', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prorroga',
            name='nueva_fecha_finalizacion',
        ),
        migrations.AddField(
            model_name='contratista',
            name='consorcio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contratista',
            name='email_secundario',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='aseguradora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='plazo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prorroga',
            name='nueva_fecha_terminacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='fecha_agregado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='clase',
            field=models.CharField(blank=True, choices=[('Arrendamiento', 'Arrendamiento'), ('Cesión Derechos Patrimoniales', 'Cesión Derechos Patrimoniales'), ('Compraventa', 'Compraventa'), ('Consultoría', 'Consultoría'), ('Interadministrativo', 'Interadministrativo'), ('Obra Pública', 'Obra Pública'), ('Orden Compra Colombia Compra Eficiente', 'Orden Compra Colombia Compra Eficiente'), ('Prestación de Servicios', 'Prestación de Servicios'), ('Prestación de Servicios y Compraventa', 'Prestación de Servicios y Compraventa'), ('Prestación de Servicios y Suministro', 'Prestación de Servicios y Suministro'), ('Seguros', 'Seguros'), ('Prestación de Servicios Profesionales', 'Prestación de Servicios Profesionales'), ('Suministro', 'Suministro')], default='Sin Clase', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fuente_recursos',
            field=models.CharField(blank=True, choices=[('Recursos propios', 'Recursos propios'), ('Presupuesto de entidad nacional', 'Presupuesto de entidad nacional'), ('Regalías', 'Regalías'), ('Recursos de credito', 'Recursos de credito'), ('SGP', 'SGP'), ('No Aplica', 'No Aplica')], max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contratacion',
            field=models.CharField(choices=[('Sin Clasificar', 'Sin Clasificar'), ('Directa', 'Directa'), ('Privada', 'Privada'), ('Publica', 'Publica')], default='Sin Tipo', max_length=600),
        ),
        migrations.AlterField(
            model_name='prorroga',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='prorroga',
            name='justificacion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.modificacion'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='reinicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.reinicio'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='suspension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.suspension'),
        ),
    ]
