# Generated by Django 5.1.1 on 2024-12-15 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0018_modificacion_reinicio_suspension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='adicion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='modificacion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='prorroga',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='reinicio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='suspension',
        ),
        migrations.AddField(
            model_name='adicion',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adiciones', to='workspace.contrato'),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='workspace.contrato'),
        ),
        migrations.AddField(
            model_name='prorroga',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prorrogas', to='workspace.contrato'),
        ),
        migrations.AddField(
            model_name='reinicio',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reinicios', to='workspace.contrato'),
        ),
        migrations.AddField(
            model_name='suspension',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspensiones', to='workspace.contrato'),
        ),
    ]
