# Generated by Django 5.1.1 on 2024-12-15 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0019_remove_contrato_adicion_remove_contrato_modificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aclaracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subscripcion', models.DateField(null=True)),
                ('motivo', models.CharField(max_length=250, null=True)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aclaraciones', to='workspace.contrato')),
            ],
        ),
    ]
