# Generated by Django 5.1.1 on 2024-12-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0020_aclaracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado_contrato',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Suspendido', 'Suspendido'), ('Liquidado', 'Liquidado')], default='Activo', max_length=200),
        ),
    ]
