# Generated by Django 5.1.1 on 2024-12-23 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0021_alter_contrato_estado_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ampliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subscripcion', models.DateField(null=True)),
                ('fecha_terminacion', models.DateField(null=True)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ampliaciones', to='workspace.contrato')),
            ],
        ),
    ]
